from sqlalchemy import Column, Integer, String, Text, DateTime
from sqlalchemy.sql import func
from .database import Base

class Journal(Base):
    """
    Journal ORM model for storing journal entries.

    Attributes:
        id: Auto-incrementing primary key
        client_id: Unique ID generated by frontend (for offline sync)
        prompt: The prompt question shown to the user
        text: The journal entry text written by the user
        timestamp: User's creation timestamp (milliseconds since epoch)
        created_at: Server timestamp when record was created
        updated_at: Server timestamp when record was last updated
    """
    __tablename__ = "journals"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    client_id = Column(String, unique=True, nullable=False, index=True)
    prompt = Column(Text, nullable=False)
    text = Column(Text, nullable=False)
    timestamp = Column(Integer, nullable=False, index=True)  # User's creation time
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now(), server_default=func.now())

    def __repr__(self):
        return f"<Journal(id={self.id}, client_id={self.client_id}, timestamp={self.timestamp})>"
